### ISSUE TITLE
Do we need to clear setTimeout as well ?

### ISSUE THREAD

**Issue by amitpatil321** [littlee/eslint-plugin-clean-timer#4]
Since setTimeout runs only one time, Do we really need to clear it ? How can I ignore this eslint rule ?

**Comment by rostamiani** [comment]
Use this forked version:
```
npm i eslint-plugin-clean-interval
```
It removed `timeout` from rules

**Comment by vladpuz** [comment]
Yes, you need to clear the setTimeout if you want the garbage collector to work efficiently. The garbage collector will not be able to clear the external variables until the callback inside the setTimeout is executed or canceled, because they are reachable.

https://javascript.info/settimeout-setinterval

![image](https://github.com/littlee/eslint-plugin-clean-timer/assets/52296792/c68913b3-bd28-4639-9a80-642b609e79cc)
